# Generated by Django 5.0.2 on 2024-02-16 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('description', models.TextField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('amount_type', models.CharField(choices=[('income', 'Income'), ('expenses', 'Expenses')], max_length=8)),
                ('category', models.CharField(choices=[('housing', 'Housing'), ('utilities', 'Utilities'), ('groceries', 'Groceries'), ('transportation', 'Transportation'), ('health care', 'Health Care'), ('others', 'Others')], max_length=14)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
