# Generated by Django 5.0.2 on 2024-02-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
    ]
